version: '3.8'

networks:
  web:
    driver: bridge

services:
  php-fpm-xdebug:
    container_name: php-fpm-xdebug
    tty: true # Enables debugging capabilities when attached to this container.
    build:
      context: ./fpm
      dockerfile: Dockerfile
    ports:
      - 9975:9000
    restart: unless-stopped
    volumes:
      - ./sites:/var/www/
      # Pool php fpm слушает 9001 порт
      - ./fpm-pool/pool-custom.conf:/etc/php/8.2/fpm/pool.d/pool-custom.conf
      # Конфиги для php
      - ./fpm/conf.d/xdebug.ini:/etc/php/8.2/mods-available/xdebug.ini
    networks:
      - web

  php-fpm-exporter-xdebug:
    image: bakins/php-fpm-exporter:v0.6.1
    container_name: php-fpm-exporter-xdebug
    restart: unless-stopped
    command: [ "--endpoint", "http://nginx-xdebug/status-fpm", "--addr", "0.0.0.0:8080" ]
    ports:
      - "9255:8080"
    networks:
      - web
    depends_on:
      - nginx-xdebug

  nginx-xdebug:
    image: nginx:latest
    container_name: nginx-xdebug
    ports:
      - "8085:80"
    networks:
      - web
    restart: unless-stopped
    volumes:
      #  - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Это конфиги для хостов
      - ./hosts:/etc/nginx/templates
      # Это файлы сайтов
      - ./sites:/var/www/
      - ./logs/nginx:/var/log/nginx
